version: '3'
services:
  dynamodb:
    image: 'amazon/dynamodb-local:1.24.0'
  test:
    build:
      context: .
      dockerfile: dockerfile.test
    volumes:
      - data:/app
    working_dir: /app
    user: ${MY_USER:-root}
    depends_on:
      - dynamodb
    command: 'bash ./test.sh'
volumes:
  data:
